### Obtain token JWT
POST http://127.0.0.1:8000/recipes/api/token/
Content-Type: application/json

{
  "username": "YourUsername",
  "password": "YourPassword"
}

### update token JWT
POST http://127.0.0.1:8000/recipes/api/token/refresh/
Content-Type: application/json

{
  "refresh": "YourRefreshTokenHere"
}

### verify validation token JWT
POST http://127.0.0.1:8000/recipes/api/token/verify/
Content-Type: application/json

{
  "token": "YourAccessTokenHere"
}