# Generated by Django 5.2.4 on 2025-10-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('min', 'Minutos'), ('h', 'Horas'), ('s', 'Segundos')], default='minutos', max_length=65, verbose_name='Tempo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('porcao', 'Porções'), ('fatia', 'Fatias'), ('unidade', 'Unidades'), ('pessoa', 'Pessoas')], default='porções', max_length=65, verbose_name='Unidade do rendimento'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category', verbose_name='Categoria'),
        ),
    ]
