# Generated by Django 5.2.4 on 2025-10-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
