# Generated by Django 5.2.4 on 2025-12-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_published',
        ),
    ]
